apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  params:
    - name: app-name
      type: string
      default: counter-service
    - name: build-image
      type: string
      default: counter-service:latest
    - name: namespace
      type: string
      default: ci-cd-project
  workspaces:
    - name: source
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: source
    
    - name: git-clone
      taskRef:
        name: git-clone
      params:
        - name: url
          value: https://github.com/fernandoog/ci-cd-final-project.git
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: source
      runAfter:
        - cleanup
    
    - name: flake8-linting
      taskRef:
        name: flake8
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - git-clone
    
    - name: nose-tests
      taskRef:
        name: nose
      params:
        - name: args
          value: "-v --with-spec --spec-color --with-coverage --cover-package=service"
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - flake8-linting
    
    - name: buildah-build
      taskRef:
        name: buildah
      params:
        - name: IMAGE
          value: $(params.build-image)
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
      workspaces:
        - name: source
          workspace: source
      runAfter:
        - nose-tests
    
    - name: deploy-app
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -
            oc expose deployment $(params.app-name) --port=8000
            oc set env deployment/$(params.app-name) PORT=8000
      runAfter:
        - buildah-build
